# Standard Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

# Data

In [2]:
path_to_file = "./Data/shakespeare.txt"
text = open(path_to_file, "r").read()
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [3]:
vocab = sorted(set(text))
print(len(vocab),vocab)

84 ['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


# Encoding: Letters to Numbers

So there are 84 unique characters in the shakespear corpus. We will use one-hot encoding to represent each character as a vector of length 84. The vector will have all zeros except for the index corresponding to the character, which will be 1.

In [4]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [5]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [6]:
char_to_ind["H"]

33

In [7]:
ind_to_char = np.array(vocab)

In [8]:
ind_to_char[33]

'H'

In [9]:
encoded_text = np.array([char_to_ind[c] for c in text])
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

so there are around 5.5 Million words inside the shakespeare.txt file

In [10]:
len(encoded_text)

5445609

In [11]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [12]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [13]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


# Exploring Patterns

In [14]:
len("From fairest creatures we desire increase,")

42

In [15]:
len("""From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,""")

131

There is a rhyme in almost every 3rd line, so in order for our model to find patterns, it must read atleast 3 lines: around 130 characters

In [16]:
seq_length = 130

In [17]:
total_seq = len(text) // (seq_length + 1)
total_seq  

41569

# Converting to Tensors: Creating Batches
SO we can easily feed them to the model

In [18]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [19]:
for char in char_dataset.take(500):
    print(char.numpy())

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


# Creating Sequences from the Tensor

In [20]:
sequences = char_dataset.batch(seq_length + 1, drop_remainder=True) 
# Because of 0 indexing, seq_length + 1
# len(text) / seq_length == 45005.03 so dropping that 0.03

Now that we have our sequences, we will perform the following steps for each one to create our target text sequences:

1. Grab the input text sequence
2. Assign the target text sequence as the input text sequence shifted by one step forward
3. Group them together as a tuple

In [21]:
def create_seq_targets(seq):
    input_txt = seq[:-1] # Hello my nam
    target_txt = seq[1:] # ello my name
    return input_txt, target_txt

In [22]:
dataset = sequences.map(create_seq_targets)

## Example Input Sequence and Target Text

Target has extra whitespace

In [23]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75
  1 56 74  1 75 63 60  1 73 64]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the ri


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1
 56 74  1 75 63 60  1 73 64 71]
                     1
  From fairest creatures we desire increase,
  Tha

# Generating training batches

Now that we have the actual sequences, we will create the batches, we want to shuffle these sequences into a random order, so the model doesn't overfit to any section of the text, but can instead generate characters given any seed text.

In [24]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [25]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(128, 130), dtype=tf.int32, name=None), TensorSpec(shape=(128, 130), dtype=tf.int32, name=None))>

See the shape of dataset is ( (128,130) , (128,130) ) because it is 128 (batch_size) unique sequences of length 130 characters.

There are 2 sets because 1st is input sequence and the other one is target sequence.

# Preparing the Loss Function

In [26]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [27]:
vocab_size = len(vocab)
vocab_size

84

Because our data is one hot encoded we are going to use sparse_cross_entropy instead of cross_entropy

In [28]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [29]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2.384

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.

**INBUILT FUNCTION**
We want logits = True.

In [35]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

# Creating The Model

We are adding a big single RNN layer instead we can also do many smaller RNN layers 

- `vocab_size`: Size of the vocabulary (total number of unique words or tokens in the text corpus).
- `embed_dim`: Dimensionality of word embeddings (length of the dense vector representation of words).

- `rnn_neurons`: The number of neurons or units in the GRU layer. It determines the dimensionality of the GRU's output and internal state.
- `return_sequences`: A boolean parameter that specifies whether the GRU layer should return the full sequence of outputs (`True`) or just the last output (`False`) when processing a sequence.
- `stateful`: If `True`, the states from the previous batch will be used as the initial states for the current batch.
- `recurrent_initializer`: The initialization method for the recurrent weights of the GRU. In this case, 'glorot_uniform' is used, which is a variation of the Xavier/Glorot uniform initializer for the recurrent weights.

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    
    model = Sequential()
    
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    
    # Recurrent_initializer = "glorot_uniform" just research, nothing to explain
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [37]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [38]:
model = create_model(
    vocab_size=vocab_size,
    embed_dim=embed_dim,
    rnn_neurons=rnn_neurons,
    batch_size=batch_size)

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_1 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_1 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Training The Model

In [39]:
for input_example_batch, target_example_batch in dataset.take(1):

    # Predict off some random batch
    example_batch_predictions = model(input_example_batch)

    # Display the dimensions of the predictions
    print(example_batch_predictions.shape,
        " <=== (batch_size, sequence_length, vocab_size)")

example_batch_predictions


(128, 130, 84)  <=== (batch_size, sequence_length, vocab_size)


<tf.Tensor: shape=(128, 130, 84), dtype=float32, numpy=
array([[[ 2.32748548e-03, -4.01643943e-03,  9.90648987e-05, ...,
          1.39388442e-03,  4.34970949e-03,  4.51245159e-03],
        [-5.35512250e-03,  1.44164555e-03, -2.41996255e-04, ...,
          4.21193475e-03,  6.97787327e-04,  7.85241649e-03],
        [ 3.14112846e-03, -3.39319766e-03,  8.97041522e-03, ...,
          4.38333582e-03, -2.63108267e-03,  1.44945942e-02],
        ...,
        [ 1.48687446e-02,  1.37571304e-03, -1.12667652e-02, ...,
         -3.48050380e-05, -1.08929714e-02, -4.19229409e-03],
        [ 1.63475554e-02,  2.53165001e-03, -1.10104848e-02, ...,
          1.11210172e-03, -1.06050512e-02, -4.70345467e-03],
        [ 1.72748789e-02,  3.21802683e-03, -1.04734395e-02, ...,
          1.73274032e-03, -1.03259888e-02, -4.90253605e-03]],

       [[ 2.32748548e-03, -4.01643943e-03,  9.90648987e-05, ...,
          1.39388442e-03,  4.34970949e-03,  4.51245159e-03],
        [ 3.75181343e-03, -1.46720130e-02,  2.3

In [40]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices

<tf.Tensor: shape=(130, 1), dtype=int64, numpy=
array([[19],
       [13],
       [76],
       [ 7],
       [ 4],
       [59],
       [14],
       [65],
       [24],
       [33],
       [30],
       [60],
       [19],
       [38],
       [50],
       [ 2],
       [50],
       [54],
       [80],
       [11],
       [77],
       [71],
       [27],
       [ 7],
       [40],
       [15],
       [ 4],
       [73],
       [58],
       [51],
       [61],
       [26],
       [69],
       [70],
       [ 8],
       [73],
       [28],
       [ 2],
       [ 1],
       [62],
       [ 2],
       [ 8],
       [42],
       [36],
       [50],
       [38],
       [20],
       [24],
       [26],
       [11],
       [ 6],
       [21],
       [48],
       [36],
       [72],
       [65],
       [16],
       [28],
       [70],
       [38],
       [25],
       [ 2],
       [49],
       [55],
       [ 2],
       [20],
       [79],
       [50],
       [77],
       [10],
       [55],
       [69],
       [33],
   

In [41]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()
sampled_indices

array([19, 13, 76,  7,  4, 59, 14, 65, 24, 33, 30, 60, 19, 38, 50,  2, 50,
       54, 80, 11, 77, 71, 27,  7, 40, 15,  4, 73, 58, 51, 61, 26, 69, 70,
        8, 73, 28,  2,  1, 62,  2,  8, 42, 36, 50, 38, 20, 24, 26, 11,  6,
       21, 48, 36, 72, 65, 16, 28, 70, 38, 25,  2, 49, 55,  2, 20, 79, 50,
       77, 10, 55, 69, 33, 58, 52, 27, 12,  8,  9, 39, 58, 17, 50, 63, 64,
       50, 61, 23, 76, 29, 49, 14, 59, 26, 43, 41, 26,  6,  1, 15, 77, 71,
       36, 76, 49, 27,  7, 25, 47, 47, 19,  9, 13, 51, 58, 35, 71,  1, 26,
        5, 22, 46, 73, 21, 69, 53, 39,  1, 14, 44], dtype=int64)

In [42]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

old acquaintance tell.  
    For thee, against my self I'll vow debate,
    For I must ne'er love him whom thou dost hate.


     


Next Char Predictions: 

82u)&d3j>HEe8MY!Y_y0vpB)O4&rcZfAno,rC! g!,QKYM9>A0(:WKqj5CoM?!X`!9xYv.`nHc[B1,-Nc6YhiYf<uDX3dARPA( 4vpKuXB)?VV8-2ZcJp A';Ur:n]N 3S


After confirming the dimensions are working, let's train our network!

In [43]:
epochs = 30
model.fit(dataset,epochs=epochs)

Epoch 1/30
324/324 [==============================] - 93s 274ms/step - loss: 2.6032
Epoch 2/30
324/324 [==============================] - 93s 274ms/step - loss: 1.8046
Epoch 3/30
324/324 [==============================] - 87s 260ms/step - loss: 1.5144
Epoch 4/30
324/324 [==============================] - 85s 254ms/step - loss: 1.3740
Epoch 5/30
324/324 [==============================] - 84s 253ms/step - loss: 1.2994
Epoch 6/30
275/324 [========================>.....] - ETA: 12s - loss: 1.2567

KeyboardInterrupt: 