# Standard Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

# Data

In [2]:
path_to_file = "./Data/shakespeare.txt"
text = open(path_to_file, "r").read()
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [3]:
vocab = sorted(set(text))
print(len(vocab),vocab)

84 ['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


# Encoding: Letters to Numbers

So there are 84 unique characters in the shakespear corpus. We will use one-hot encoding to represent each character as a vector of length 84. The vector will have all zeros except for the index corresponding to the character, which will be 1.

In [4]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [5]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [6]:
char_to_ind["H"]

33

In [7]:
ind_to_char = np.array(vocab)

In [8]:
ind_to_char[33]

'H'

In [9]:
encoded_text = np.array([char_to_ind[c] for c in text])
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

so there are around 5.5 Million words inside the shakespeare.txt file

In [10]:
len(encoded_text)

5445609

In [11]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [12]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [13]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


# Exploring Patterns

In [14]:
len("From fairest creatures we desire increase,")

42

In [15]:
len("""From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,""")

131

There is a rhyme in almost every 3rd line, so in order for our model to find patterns, it must read atleast 3 lines: around 130 characters

In [16]:
seq_length = 130

In [17]:
total_seq = len(text) // (seq_length + 1)
total_seq  

41569

# Converting to Tensors: Creating Batches
SO we can easily feed them to the model

In [18]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [19]:
for char in char_dataset.take(500):
    print(char.numpy())

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


# Creating Sequences from the Tensor

In [20]:
sequences = char_dataset.batch(seq_length + 1, drop_remainder=True) 
# Because of 0 indexing, seq_length + 1
# len(text) / seq_length == 45005.03 so dropping that 0.03

Now that we have our sequences, we will perform the following steps for each one to create our target text sequences:

1. Grab the input text sequence
2. Assign the target text sequence as the input text sequence shifted by one step forward
3. Group them together as a tuple

In [21]:
def create_seq_targets(seq):
    input_txt = seq[:-1] # Hello my nam
    target_txt = seq[1:] # ello my name
    return input_txt, target_txt

In [22]:
dataset = sequences.map(create_seq_targets)

## Example Input Sequence and Target Text

Target has extra whitespace

In [23]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75
  1 56 74  1 75 63 60  1 73 64]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the ri


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1
 56 74  1 75 63 60  1 73 64 71]
                     1
  From fairest creatures we desire increase,
  Tha

# Generating training batches

Now that we have the actual sequences, we will create the batches, we want to shuffle these sequences into a random order, so the model doesn't overfit to any section of the text, but can instead generate characters given any seed text.

In [24]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [25]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(128, 130), dtype=tf.int32, name=None), TensorSpec(shape=(128, 130), dtype=tf.int32, name=None))>

See the shape of dataset is ( (128,130) , (128,130) ) because it is 128 (batch_size) unique sequences of length 130 characters.

There are 2 sets because 1st is input sequence and the other one is target sequence.

# Preparing the Loss Function

In [26]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [27]:
vocab_size = len(vocab)
vocab_size

84

Because our data is one hot encoded we are going to use sparse_cross_entropy instead of cross_entropy

In [28]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [29]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2.384

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.

**INBUILT FUNCTION**
We want logits = True.

In [30]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

# Creating The Model

We are adding a big single RNN layer instead we can also do many smaller RNN layers 

- `vocab_size`: Size of the vocabulary (total number of unique words or tokens in the text corpus).
- `embed_dim`: Dimensionality of word embeddings (length of the dense vector representation of words).

- `rnn_neurons`: The number of neurons or units in the GRU layer. It determines the dimensionality of the GRU's output and internal state.
- `return_sequences`: A boolean parameter that specifies whether the GRU layer should return the full sequence of outputs (`True`) or just the last output (`False`) when processing a sequence.
- `stateful`: If `True`, the states from the previous batch will be used as the initial states for the current batch.
- `recurrent_initializer`: The initialization method for the recurrent weights of the GRU. In this case, 'glorot_uniform' is used, which is a variation of the Xavier/Glorot uniform initializer for the recurrent weights.

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    
    model = Sequential()
    
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    
    # Recurrent_initializer = "glorot_uniform" just research, nothing to explain
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [32]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [33]:
model = create_model(
    vocab_size=vocab_size,
    embed_dim=embed_dim,
    rnn_neurons=rnn_neurons,
    batch_size=batch_size)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


# Training The Model

In [34]:
for input_example_batch, target_example_batch in dataset.take(1):

    # Predict off some random batch
    example_batch_predictions = model(input_example_batch)

    # Display the dimensions of the predictions
    print(example_batch_predictions.shape,
        " <=== (batch_size, sequence_length, vocab_size)")

example_batch_predictions


(128, 130, 84)  <=== (batch_size, sequence_length, vocab_size)


<tf.Tensor: shape=(128, 130, 84), dtype=float32, numpy=
array([[[-5.4480555e-04,  5.4546297e-03, -2.4957554e-03, ...,
         -1.4721558e-03, -1.0096860e-03, -4.5793606e-03],
        [-8.1909867e-04,  7.8510912e-03, -3.4928177e-03, ...,
         -2.1210737e-03, -4.0509994e-04, -6.2187877e-03],
        [-9.9749118e-04,  8.9958450e-03, -3.9262827e-03, ...,
         -2.3590368e-03,  3.3635460e-04, -6.6468641e-03],
        ...,
        [-9.5425192e-03,  7.5120917e-03,  4.1986881e-03, ...,
         -2.4512545e-03, -4.2229393e-03, -2.7720912e-03],
        [-1.2513433e-02,  8.6412709e-03,  8.9020270e-04, ...,
         -1.8901028e-03,  2.5715036e-03,  7.7130208e-03],
        [-1.0650536e-02,  7.1678227e-03, -3.1018071e-03, ...,
         -1.0832161e-02, -1.6578261e-03,  6.5392121e-03]],

       [[-3.5220666e-03, -4.8247953e-03, -7.5706060e-04, ...,
          4.8488360e-03,  5.0071785e-03,  6.5474794e-03],
        [ 1.6663829e-03, -6.6346959e-03, -5.1473891e-03, ...,
          2.6405463e-04,  3

In [35]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices

<tf.Tensor: shape=(130, 1), dtype=int64, numpy=
array([[36],
       [64],
       [30],
       [31],
       [65],
       [12],
       [62],
       [74],
       [81],
       [15],
       [50],
       [21],
       [35],
       [44],
       [57],
       [58],
       [ 5],
       [ 9],
       [ 6],
       [63],
       [ 7],
       [72],
       [83],
       [46],
       [71],
       [13],
       [42],
       [ 7],
       [ 7],
       [81],
       [16],
       [60],
       [30],
       [78],
       [61],
       [79],
       [ 1],
       [82],
       [ 4],
       [56],
       [37],
       [12],
       [51],
       [73],
       [38],
       [42],
       [19],
       [ 8],
       [ 3],
       [10],
       [78],
       [ 9],
       [26],
       [45],
       [73],
       [12],
       [19],
       [44],
       [18],
       [44],
       [39],
       [ 4],
       [50],
       [62],
       [25],
       [61],
       [30],
       [56],
       [41],
       [21],
       [21],
       [64],
       [62],
   

In [36]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()
sampled_indices

array([36, 64, 30, 31, 65, 12, 62, 74, 81, 15, 50, 21, 35, 44, 57, 58,  5,
        9,  6, 63,  7, 72, 83, 46, 71, 13, 42,  7,  7, 81, 16, 60, 30, 78,
       61, 79,  1, 82,  4, 56, 37, 12, 51, 73, 38, 42, 19,  8,  3, 10, 78,
        9, 26, 45, 73, 12, 19, 44, 18, 44, 39,  4, 50, 62, 25, 61, 30, 56,
       41, 21, 21, 64, 62, 48,  7, 43, 56, 44, 61, 30,  2, 32, 82, 30, 42,
        2, 16, 34, 30, 50, 24, 45, 26, 15, 23, 13, 82, 15, 11, 21, 42, 74,
       51, 20, 52, 36, 65, 40, 60,  4,  9, 16, 54, 55, 21, 24, 81, 50, 10,
        6,  8, 64, 78, 46, 77, 75, 71,  1, 74, 65], dtype=int64)

In [37]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

    The faults of fools but folly.
  COMINIUS. Ever right.
  CORIOLANUS. Menenius ever, ever.
  HERALD. Give way there, and go on.


Next Char Predictions: 

KiEFj1gsz4Y:JSbc'-(h)q}Up2Q))z5eEwfx |&aL1ZrMQ8,".w-ATr18S7SN&Yg?fEaP::igW)RaSfE!G|EQ!5IEY>TA4<2|40:QsZ9[KjOe&-5_`:>zY.(,iwUvtp sj


After confirming the dimensions are working, let's train our network!

In [38]:
# epochs = 30
# model.fit(dataset,epochs=epochs)

Epoch 1/30


324/324 [==============================] - 79s 231ms/step - loss: 2.5714
Epoch 2/30
324/324 [==============================] - 80s 243ms/step - loss: 1.7418
Epoch 3/30
324/324 [==============================] - 81s 246ms/step - loss: 1.4656
Epoch 4/30
324/324 [==============================] - 81s 246ms/step - loss: 1.3441
Epoch 5/30
324/324 [==============================] - 83s 250ms/step - loss: 1.2789
Epoch 6/30
324/324 [==============================] - 81s 245ms/step - loss: 1.2377
Epoch 7/30
324/324 [==============================] - 82s 247ms/step - loss: 1.2067
Epoch 8/30
324/324 [==============================] - 82s 247ms/step - loss: 1.1832
Epoch 9/30
324/324 [==============================] - 81s 246ms/step - loss: 1.1626
Epoch 10/30
324/324 [==============================] - 81s 245ms/step - loss: 1.1450
Epoch 11/30
324/324 [==============================] - 82s 247ms/step - loss: 1.1292
Epoch 12/30
324/324 [==============================] - 82s 247ms/step - loss: 1.1147


In [39]:
# Saving the model:
# model.save('./model/text_generation.h5')

In [43]:
# Loading the model:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('./model/text_generation.h5')

# Generating Text:
Currently our model only expects 128 sequences at a time. We can create a new model that only expects a `batch_size=1`. We can create a new model with this batch size, then load our saved models weights. Then call .build() on the model:

In [44]:
model.build(tf.TensorShape([1, None]))

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_1 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_1 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [46]:
def generate_text(model, start_seed, gen_size=100, temp=1.0):
    '''
    model: Trained Model to Generate Text
    start_seed: Intial Seed text in string form
    gen_size: Number of characters to generate

    Basic idea behind this function is to take in some seed text, format it so
    that it is in the correct shape for our network, then loop the sequence as
    we keep adding our own predicted characters. Similar to our work in the RNN
    time series problems.
    '''

    # Number of characters to generate
    num_generate = gen_size

    # Vecotrizing starting seed text
    input_eval = [char_to_ind[s] for s in start_seed]

    # Expand to match batch format shape
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty list to hold resulting generated text
    text_generated = []

    # Temperature effects randomness in our resulting text
    # The term is derived from entropy/thermodynamics.
    # The temperature is used to effect probability of next characters.
    # Higher probability == lesss surprising/ more expected
    # Lower temperature == more surprising / less expected

    temperature = temp

    # Here batch size == 1
    model.reset_states()

    for i in range(num_generate):

        # Generate Predictions
        predictions = model(input_eval)

        # Remove the batch shape dimension
        predictions = tf.squeeze(predictions, 0)

        # Use a cateogircal disitribution to select the next character
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(
            predictions, num_samples=1)[-1, 0].numpy()

        # Pass the predicted charracter for the next input
        input_eval = tf.expand_dims([predicted_id], 0)

        # Transform back to character letter
        text_generated.append(ind_to_char[predicted_id])

    return (start_seed + ''.join(text_generated))

In [47]:
print(generate_text(model,"flower",gen_size=1000))

flowers,
    As perfect is upon him.
  Corn. What amaze her silver, till the livele court herself wills make enough
    on thee.
  TROILUS. Weds, sick finds of love.
  FRANCISCE. Why, what a man is this?
  PROAPETRSSANIO. Well, believe the heaven speaks so;
    And so have I
    And my poor corse, and not by vow in wars,
    So your ostentation, supple your act,
    Made good her worthiness, better brief with your age.
  ARCHBISHOP. Seven gentlemen; this shapes creat the at,
               In thy shame is laid upon his forward.  

                    Enter CURTH

 CAMPEIU.
                The Goths have no advantage on yond title rectify
    To commend his likely. Thy looks lieatch be otherwise.-
  It seems you like a bird, whose horror help as he were,
    Is't to redeem or fault?
  FIRST SERVANT. Ay, but not die. Your honours is a goodly birds to fight
    Left is but his own burial. O my brother Troyan?
  MIRANDA. Yes; ere I could work in: and, indeed,  
    As your gold-much gainst